exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "idea",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv"
]

line-length = 100
indent-width = 4

[lint]
select = [
    "E", # Error
    "W", # Pycodestyle
    "I", # Isort,
    "C", # Complexity
    "UP", # Unused imports and variables
    "B", # Bugbear
    "E4", "E7", "E9", # Flake8
    "ASYNC", # Flake8-async
    "TD", # Catch invalid todo annotation
    "F", # Pyflakes
    "C90", # McCabe complexity
    "N", # pep8-naming
    "D", # Pydocstyle
    "ANN", # Pytype annotations
    "S", # Bandit
    "COM", # Commas
    "C4", # Comprehensions
    "ISC", # Implicit string concat
    "PIE", # Unnecessary code
    "T20", # Catch prints
    "RSE", # Checks raise statements
    "RET", # Checks return statements
    "SLF", # Self checks
    "SIM", # Simplificator
    "PTH", # Pathlib checks
    "ERA", # Checks for commented out code
]

ignore = [
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "D211", # No blank lines allowed before class docstring
    "F403", # Unable to detect undefined name
    "D401", # First line should be in imperative mood
    "D104", # Missing docstring in public package
    "D100", # Missing docstring in public module
    "D212", # Multi-line docstring summary should start at the first line
    "D106", # Missing docstring in public nested class
    "D205", # 1 blank line required between summary line and description
    "D200", # One-line docstring should fit on one line with quotes
    "D202", # No blank lines allowed after function docstring
    "C901", # McCabe complexity
    "ANN401", # typing.Any are disallowed in `**kwargs
    "ANN002", # Missing type annotation for *args
    "ANN003", # Missing type annotation for **kwargs
    "S112", # `try`-`except`-`continue` detected, consider logging the exception,
]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

docstring-code-format = true
docstring-code-line-length = "dynamic"

[lint.mccabe]
max-complexity = 10

[lint.flake8-quotes]
docstring-quotes = "single"

[lint.pydocstyle]
convention = "pep257"
ignore-decorators = ["typing.overload"]
